services:
  db:
    image: postgres:15
    container_name: school_db_dev
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
    ports:
      - "5433:5432"   # istersen kapatabilirsin; sadece dışarıdan erişmek istersen açık kalsın
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 3s
      retries: 10

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: digitalpanel_backend_dev
    env_file: .env.dev
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  db_data_dev:
